image: python:3.8

stages:
  - check
  - test

check:
  stage: check
  script:
    - pip install pylint
    - pylint **/*.py

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest
