# image: python: 3.8

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - pip install pylint
    - pylint **/*.py

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest
