name: Unit Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint flake8

    - name: Lint with pylint
      run: python -m pylint **/*.py
    # - name: Lint with flake8
    #   run: flake8 .

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install -r requirements.txt

    - name: Run tests
      run: python3 -m unittest
